font_family      family="FiraCode Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_features        FiraCodeNF-Reg +liga +calt +cv01 +ss02 +ss04 +ss05
font_features        FiraCodeNF-Bold +liga +calt +cv01 +ss02 +ss04 +ss05

symbol_map U+4E00-U+9FFF,U+3400-U+4DBF FZLiuGongQuanKaiShuJF
