if [[ -x /opt/homebrew/bin/brew ]] \
  && [[ -z ${HOMEBREW_PREFIX-} || -z ${HOMEBREW_CELLAR-} || -z ${HOMEBREW_REPOSITORY-} ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

if [[ -o interactive && -t 1 && -z ${ZSH_WELCOME_SHOWN-} ]]; then
  export ZSH_WELCOME_SHOWN=1
  (( ${+commands[fastfetch]} )) && fastfetch
  echo "
                (__) 
                 (oo) 
           /------\\/ 
          / |    ||   
         *  /\\---/\\ 
            ~~   ~~   
...\\\"Have you mooed today?\\\"..."
  (( ${+commands[fortune]} )) && fortune
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  github
  sudo
  vscode
  zsh-syntax-highlighting
  zsh-autosuggestions
  z
  command-not-found
  colored-man-pages
  vi-mode
  extract
  cp
  #git-open
  per-directory-history #ctrl + g
  safe-paste
  history-substring-search
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
alias zshconfig="vim ~/.zshrc"
alias ohmyzsh"vim ~/.oh-my-zsh"

alias rm="trash"

alias ls="eza"
alias ll="eza -l"
alias tree="eza -T"

alias cat="bat"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

alias :q="exit"
alias :Q="exit"

bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down

alias VIM="sudo vim"
alias vim="nvim"
alias neovim="nvim"

alias tl="tmux list-sessions"
alias tkss="tmux kill-session -t"
alias ta="tmux attach -t"
alias ts="tmux new-session -s"

eval "$(pay-respects zsh --alias)"
alias fuck="pay-respects"

alias CMAKE="cmake -GNinja -DCMAKE_C_COMPILER=/opt/homebrew/bin/gcc-15 -DCMAKE_CXX_COMPILER=/opt/homebrew/bin/g++-15 "

export NIX_PATH="/Users/hc/.nixpkgs:/nix/var/nix/profiles/per-user/root/channels"

# ==========================================
# zoxide 配置与别名
# ==========================================

# 初始化 zoxide，将基础命令替换为 cd
eval "$(zoxide init --cmd cd zsh)"

# 1. 交互式选择跳转 (依赖 fzf)

# 2. 数据库与记录管理
alias zq="zoxide query"            # 仅查询路径，不执行跳转
alias zls="zoxide query -l"        # 按权重大小列出所有被 zoxide 记录的目录
alias zrm="zoxide remove"          # zrm <路径>：手动从数据库移除某个路径
alias zrm_current="zoxide remove ." # 从记录中移除当前所在目录

# 3. 交互式清理失效目录
# 使用 fzf 交互式多选 (Tab键) 你想从 zoxide 数据库中删除的目录
alias zrmx="zoxide query -l | fzf -m --prompt='Remove directory> ' | xargs -I {} zoxide remove {}"

# 4. 结合你常用编辑器的跳转函数 (Emacs / Neovim)

# zv: 跳转到模糊匹配的目录，并立即用 Neovim 打开
zv() {
    local target_dir
    target_dir=$(zoxide query "$@")
    if [[ -n "$target_dir" ]]; then
        cd "$target_dir" || return
        nvim .
    else
        echo "❌ 未找到匹配的目录: $@"
    fi
}

# ze: 跳转到模糊匹配的目录，并立即用 Emacs 打开
ze() {
    local target_dir
    target_dir=$(zoxide query "$@")
    if [[ -n "$target_dir" ]]; then
        cd "$target_dir" || return
        # 根据你个人的 Emacs 启动习惯可以修改这行，例如只是 `emacs .`
        emacsclient -nw . 
    else
        echo "❌ 未找到匹配的目录: $@"
    fi
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f /opt/homebrew/etc/profile.d/autojump.sh ] && . /opt/homebrew/etc/profile.d/autojump.sh

LIBRARY_PATH="$LIBRARY_PATH:/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib"
export PATH="/opt/homebrew/opt/ruby/bin:$PATH:/Library/TeX/texbin"
export LDFLAGS="-L/opt/homebrew/opt/ruby/lib"
export CPPFLAGS="-I/opt/homebrew/opt/ruby/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/ruby/lib/pkgconfig"

alias docker-tty-mac="docker run -it --rm --privileged --pid=host alpine:edge nsenter -t 1 -m -u -n -i sh"

# vcpkg
export VCPKG_ROOT="/Users/hc/Hc/SOURCE/vcpkg"

set rtp+=/opt/homebrew/opt/fzf

alias CVshare="natclip -c -i=10.31.1.165"
export MAPLE="/Library/Frameworks/Maple.framework/Versions/2024"
export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:/Library/Frameworks/Maple.framework/Versions/2024/bin.APPLE_ARM64_MACOS"

alias Sagepython="/private/var/tmp/sage-10.5-current/local/var/lib/sage/venv-python3.12.5/bin/python3"
alias Sagepython-config="/private/var/tmp/sage-10.5-current/local/var/lib/sage/venv-python3.12.5/bin/python3-config"
export MYGIT="ssh://Aaron-git"

function y() {
  local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
  yazi "$@" --cwd-file="$tmp"
  if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
    builtin cd -- "$cwd"
  fi
  rm -f -- "$tmp"
}

vterm_printf() {
  if [ -n "$TMUX" ] &&
    { [ "${TERM%%-*}" = "tmux" ] ||
      [ "${TERM%%-*}" = "screen" ]; }; then
    # Tell tmux to pass the escape sequences through
    printf "\ePtmux;\e\e]%s\007\e\\" "$1"
  elif [ "${TERM%%-*}" = "screen" ]; then
    # GNU screen (screen, screen-256color, screen-256color-bce)
    printf "\eP\e]%s\007\e\\" "$1"
  else
    printf "\e]%s\e\\" "$1"
  fi
}

alias org="yazi ~/.emacs.d/Org"
alias config_nix="yazi ~/.nixpkgs/"
alias config_emacs="yazi ~/.emacs.d/"
alias e='emacsclient -c -a ""'  # GUI
alias et='emacsclient -t -a ""' # TTY

eval "$(direnv hook zsh)"
